export const listAGVs = [
  {
    agv_id: "AGV001",
    max_speed: "5 m/s",
    max_battery: "100%",
    max_load: "500 kg",
    guidance_type: "Laser",
    end_point: "Warehouse A",
    is_connected: "Yes",
    is_busy: "No",
  },
  {
    agv_id: "AGV002",
    max_speed: "4 m/s",
    max_battery: "80%",
    max_load: "400 kg",
    guidance_type: "Magnetic",
    end_point: "Warehouse B",
    is_connected: "Yes",
    is_busy: "Yes",
  },
  {
    agv_id: "AGV003",
    max_speed: "6 m/s",
    max_battery: "90%",
    max_load: "600 kg",
    guidance_type: "Vision",
    end_point: "Warehouse C",
    is_connected: "No",
    is_busy: "No",
  },
  {
    agv_id: "AGV004",
    max_speed: "5.5 m/s",
    max_battery: "75%",
    max_load: "550 kg",
    guidance_type: "Laser",
    end_point: "Warehouse D",
    is_connected: "Yes",
    is_busy: "No",
  },
  {
    agv_id: "AGV005",
    max_speed: "4.5 m/s",
    max_battery: "85%",
    max_load: "450 kg",
    guidance_type: "Magnetic",
    end_point: "Warehouse E",
    is_connected: "No",
    is_busy: "Yes",
  },
  {
    agv_id: "AGV006",
    max_speed: "5.2 m/s",
    max_battery: "95%",
    max_load: "520 kg",
    guidance_type: "Vision",
    end_point: "Warehouse F",
    is_connected: "Yes",
    is_busy: "No",
  },
];
