export const listAGVs = [
  {
    agv_id: "1",
    max_speed: "5",
    max_battery: "100",
    max_load: "20",
    guidance_type: "Laser",
    is_connected: "Yes",
    is_busy: "No",
  },
  {
    agv_id: "2",
    max_speed: "4",
    max_battery: "80",
    max_load: "19",
    guidance_type: "Magnetic",
    is_connected: "Yes",
    is_busy: "Yes",
  },
  {
    agv_id: "3",
    max_speed: "6",
    max_battery: "90",
    max_load: "25",
    guidance_type: "Vision",
    is_connected: "No",
    is_busy: "No",
  },
  {
    agv_id: "4",
    max_speed: "5.5",
    max_battery: "75",
    max_load: "20",
    guidance_type: "Laser",
    is_connected: "Yes",
    is_busy: "No",
  },
  {
    agv_id: "5",
    max_speed: "4.5",
    max_battery: "85",
    max_load: "15",
    guidance_type: "Magnetic",
    is_connected: "No",
    is_busy: "Yes",
  },
  {
    agv_id: "6",
    max_speed: "5.2",
    max_battery: "95",
    max_load: "30",
    guidance_type: "Vision",
    is_connected: "Yes",
    is_busy: "No",
  },
];
